### ISSUE TITLE
 gzip: stdin: not in gzip format tar

### ISSUE THREAD

**Issue by ChinaSilence** [neuralphene/UGATIT-data#1]
When I exec `./extract-dataset.sh`, I got
```
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

**Comment by neuralphene** [comment]
@ChinaSilence They disabled LFS on this repo because there is apparently a 1GB limit. Thus, when you clone, you're only getting the link to the tgz and not the actual tgz itself. There is no way to fix this. I recommend getting the dataset from the original repo. There are some links to a torrent in the comments. I will be deleting this repository, since it will not work without LFS.
